services:
  anekdot:
    image: ghcr.io/cupertank/anekdot-of-the-day:latest
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    environment:
      - NODE_ENV=production
